version: 2
jobs:
  build:
    docker:
      - image: openjdk:8
    steps:
      - restore_cache:
          key: sbt-cache
      - checkout
      - run:
          name: Checkout submodule
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Install sbt
          command: |
            curl -Ls https://git.io/sbt > /usr/local/bin/sbt
            chmod u+x /usr/local/bin/sbt
      - run:
          command: sbt scalafmtSbtCheck
      - run:
          command: sbt webpush-protobuf/compile webpush-protobuf-grpc/compile
      - run:
          name: sbt publishSigned
          command: |
            mkdir -p ~/.sbt/gpg
            echo $GPG_SECRET_KEY | base64 --decode > ~/.sbt/gpg/secring.asc
            sbt webpush-protobuf/publishSigned webpush-protobuf-grpc/publishSigned
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
